CREATE TABLE EMPLOYEE(
	EMP_ID VARCHAR(50),
	EMP_FIRSTNM VARCHAR(50),
	EMP_LASTNM VARCHAR(150),
	EMP_JOIN_DT DATE,
	EMAIL VARCHAR(50),
	LOCATION VARCHAR(50),
	CONTACT_DETAILS VARCHAR(50),
	CLIENT_NAME VARCHAR(50),
	WORK_GRP VARCHAR(50),
	PRIMARY KEY (EMP_ID)
);

CREATE TABLE EMP_LOGIN(
	EMP_ID VARCHAR(50),
	EMP_PASSWORD VARCHAR(50),
	PRIMARY KEY(EMP_ID)
);

INSERT INTO EMP_LOGIN VALUES
('srikar','test123');

delete from EMPLOYEE where emp_id = 'srikar';
