CREATE TABLE dbo.USER_ACCOUNT (
    EMP_ID         VARCHAR (50) NOT NULL,
    BANK_NAME      VARCHAR (50) NOT NULL,
    IFSC_CODE      VARCHAR (50) NOT NULL,
    ACCOUNT_TYPE   VARCHAR (50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR (50) NOT NULL,
    NAME_ACCOUNT   VARCHAR (50) NOT NULL,
    ID INT NOT NULL IDENTITY, 
    CONSTRAINT FK_USER_ACCOUNT_ToTable FOREIGN KEY (EMP_ID) REFERENCES dbo.EMPLOYEE (EMP_ID), 
    CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY (ID)
);

CREATE TABLE dbo.EMPLOYEE (
    EMP_ID          VARCHAR (50)  NOT NULL,
    EMP_FIRSTNM     VARCHAR (50)  NULL,
    EMP_LASTNM      VARCHAR (150) NULL,
    EMP_JOIN_DT     DATE          NULL,
    EMAIL           VARCHAR (50)  NULL,
    LOCATION        VARCHAR (50)  NULL,
    CONTACT_DETAILS VARCHAR (50)  NULL,
    CLIENT_NAME     VARCHAR (50)  NULL,
    WORK_GRP        VARCHAR (50)  NULL,
    ID INT NOT NULL IDENTITY, 
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID), 
    CONSTRAINT AK_EMPLOYEE UNIQUE (EMP_ID) 
);

CREATE TABLE dbo.EMP_LOGIN (
    EMP_ID       VARCHAR (50)  NOT NULL,
    EMP_PASSWORD VARCHAR (50)  NOT NULL,
    SEC_QUES1    VARCHAR (150) NULL,
    SEC_QUES2    VARCHAR (150) NULL,
    SEC_QUES3    VARCHAR (150) NULL,
    ID INT NOT NULL IDENTITY, 
    CONSTRAINT FK_EMP_LOGIN FOREIGN KEY (EMP_ID) REFERENCES dbo.EMPLOYEE (EMP_ID), 
    CONSTRAINT PK_EMP_LOGIN PRIMARY KEY (ID)
);

CREATE TABLE dbo.TIMESHEET(
	TIMESHEET_ID INT NOT NULL IDENTITY,
	EMP_ID VARCHAR(50) NOT NULL,
	TIMESHEET_STATUS VARCHAR(50) NOT NULL,
	STARTDATE DATE NOT NULL,
	ENDDATE DATE NOT NULL
	CONSTRAINT PK_TIMESHEET PRIMARY KEY (TIMESHEET_ID),
	CONSTRAINT FK_TIMESHEET FOREIGN KEY (EMP_ID) REFERENCES dbo.EMPLOYEE (EMP_ID)
);

CREATE TABLE dbo.TIMESHEET_DETAILS(
	ID INT NOT NULL IDENTITY,
	TIMESHEET_ID INT NOT NULL,
	DATE_HOURS DATE NOT NULL,
	NO_HOURS INT NULL,
	CONSTRAINT PK_TIMESHEET_DETAILS PRIMARY KEY (ID),
	CONSTRAINT FK_TIMESHEET_DETAILS FOREIGN KEY (TIMESHEET_ID) REFERENCES dbo.TIMESHEET (TIMESHEET_ID)
);
